### ISSUE TITLE
package-level helpfile

### ISSUE THREAD

**Issue by goldingn** [boyanangelov/sdmbench#2]
Something I always look for when getting started with a new package is a package-level helpfile, so I can do `?sdmbench` and see some general information about the package, how to get started, and see a roadmap to the available functions.

sdmbench doesn't have one of these yet, but it would be great if it did. You can create one of these with roxygen by documenting a `NULL` in a script in the `R/` folder, [like spocc does here](https://github.com/ropensci/spocc/blob/master/R/spocc-package.R).

**Comment by goldingn** [comment]
(note the `@docType package` line [here](https://github.com/ropensci/spocc/blob/master/R/spocc-package.R#L69))

**Comment by boyanangelov** [comment]
Great idea, I just added this. I think the only reason I didn't think about adding it is that it was not mentioned in H. Wickham's "R Packages" book, which was otherwise really helpful!
