### ISSUE TITLE
goodpractice checks

### ISSUE THREAD

**Issue by goldingn** [boyanangelov/sdmbench#3]
I used the [goodpractice package](https://github.com/MangoTheCat/goodpractice) to run some automated code checks of sdmbench. Below are some super minor style/robustness issues it flagged that you could change if you wanted to.

On two lines ([here](https://github.com/boyanangelov/sdmbench/blob/master/inst/shiny/server.r#L53) and [here](https://github.com/boyanangelov/sdmbench/blob/master/inst/shiny/server.r#L71)) you used `=` for assignment, instead of `<-` which you used everywhere else.

On quite a few lines of [the shiny server file](https://github.com/boyanangelov/sdmbench/blob/master/inst/shiny/server.r) there are more than 80 characters per line, which makes it a bit difficult to read (particularly [here](https://github.com/boyanangelov/sdmbench/blob/master/inst/shiny/server.r#L166-L170)). It would be worth reformatting that code to have shorter lines

On [this line](https://github.com/boyanangelov/sdmbench/blob/master/inst/shiny/server.r#L73) of the shiny server, you used the code pattern: `1:length(x)`, but `seq_along(x)` is (very mildly) preferable (in general), since in the case `x` has length 0 (e.g. an empty list), `1:length(x)` returns `c(1L, 0L)`, but `seq_along` returns `integer(0)`. 

That's all it found though, and these are very minor, which is great! I run those checks on packages quite regularly, and the reports are rarely as short as that.

**Comment by boyanangelov** [comment]
I implemented the changes, hope the code is more readable now. Thanks a lot for letting me know about the `goodpractice` package - I will have a look and start using it. I changed the code pattern as well, I didn't know it worked this way, thanks!
