### ISSUE TITLE
spellcheck

### ISSUE THREAD

**Issue by goldingn** [boyanangelov/sdmbench#6]
`devtools::spell_check()` flags a few spelling mistakes in the documentation, e.g.:

 | WORD         |   FOUND IN  |
|:------|:-----|
|acessed         |benchmark_sdm.Rd:20|
|inbalanced      |benchmark_sdm.Rd:17|
|leanring        |train_dl.Rd:10|
|occurence       |benchmark_sdm.Rd:11, customPredictFun.Rd:12, evaluate_dl.Rd:12|
|occurences     |partition_data.Rd:12|
|partitionined   |partition_data.Rd:19|
|vlaue           |get_benchmarking_data.Rd:18|

**Comment by boyanangelov** [comment]
Thanks! I ran the checks now too and fixed the language typos, leaving just the ones that are not in the dictionary (i.e. "keras", "dismo").
