### ISSUE TITLE
function examples

### ISSUE THREAD

**Issue by goldingn** [boyanangelov/sdmbench#7]
The following functions are mentioned in the package-level helpfile (note the links don't work), so will probably be used regularly, but they have only very minimal (or no) examples:
`run_sdmbench()`
`get_benchmarking_data()`
`partition_data()`
`benchmark_sdm()`
`get_best_model_results()`
`plot_sdm_map()`

It would be helpful to have more involved examples, with comments, showing the effects of the different arguments, and how you might use them in different situations. Scott's `spocc`  package is again a good example of this, the major functions all have multiple examples.

Your examples seem to have very long lines too, so it's hard to read them. I'd recommend sticking to an 80-characters-per-line limit for these too.

**Comment by boyanangelov** [comment]
Working on this, will push the edits sometime next week.

**Comment by boyanangelov** [comment]
@goldingn I just pushed improved examples for the package functions. I think they cover the functionality well, but let me know what you think.

**Comment by goldingn** [comment]
Yeah, these examples look great! Nice one!
