### ISSUE TITLE
undocumented code objects

### ISSUE THREAD

**Issue by goldingn** [boyanangelov/sdmbench#8]
`R CMD check` flagged some exported functions that are not documented:

‘customPredictFunGBM’ ‘customPredictFunKSVM’ ‘customPredictFunLogreg’ ‘customPredictFunMultinom’ ‘customPredictFunNB’ ‘customPredictFunXGB’ 

perhaps these were exported by mistake?

**Comment by goldingn** [comment]
there were  few other issues flagged by these checks (so it might be worth running those), but that was the only one I'm particularly concerned about for the JOSS review.

**Comment by boyanangelov** [comment]
Those functions are used to enable `dismo` to use `mlr` predictions. They are not going to be used directly by the user. Do you know if there is a better way to include them in the package?

I just ran the checks as well, did not see anything else which should be fixed there.

**Comment by goldingn** [comment]
Ah, I see now that you are currently exporting every function in your package: https://github.com/boyanangelov/sdmbench/blob/master/NAMESPACE#L1

You can instead explicitly export the functions that you expect the user to interact with. You could add them individually to NAMESPACE with e.g. `export(function)`, but it's normally easier to have roxygen auto-generate your NAMESPACE based on `@export` tags in the documentation for the functions you want to export. Your `importFrom` NAMESPACE lines can be generated from roxygen too, using `@importFrom` tags

**Comment by boyanangelov** [comment]
Thanks for the advice @goldingn! I just pushed the changes, now everything is generated by roxygen.
